_core_security_homepage:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: core_security_homepage}
core_security_homepage:
    path:     /{_locale}/
    defaults: { _controller: CoreSecurityBundle:Default:index, _locale: es }
